<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class DistrictsSeeder extends Seeder {
    public function run() {
        $data = [
            ['name' => "Adolfo Gonzales Chaves", 'api_districts_id' => '06014', 'api_states_id' => '06', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Concordia", 'api_districts_id' => '30015', 'api_states_id' => '30', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Federal", 'api_districts_id' => '30035', 'api_states_id' => '30', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Gualeguaychú", 'api_districts_id' => '30056', 'api_states_id' => '30', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Islas del Ibicuy", 'api_districts_id' => '30063', 'api_states_id' => '30', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Victoria", 'api_districts_id' => '30105', 'api_states_id' => '30', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Diamante", 'api_districts_id' => '30021', 'api_states_id' => '30', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Uruguay", 'api_districts_id' => '30098', 'api_states_id' => '30', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Paraná", 'api_districts_id' => '30084', 'api_states_id' => '30', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Saladillo", 'api_districts_id' => '06707', 'api_states_id' => '06', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Las Flores", 'api_districts_id' => '06455', 'api_states_id' => '06', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Rojas", 'api_districts_id' => '06686', 'api_states_id' => '06', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Escobar", 'api_districts_id' => '06252', 'api_states_id' => '06', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "José C. Paz", 'api_districts_id' => '06412', 'api_states_id' => '06', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Bahía Blanca", 'api_districts_id' => '06056', 'api_states_id' => '06', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "San Antonio de Areco", 'api_districts_id' => '06735', 'api_states_id' => '06', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Maipú", 'api_districts_id' => '06511', 'api_states_id' => '06', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "General Alvarado", 'api_districts_id' => '06280', 'api_states_id' => '06', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "General Pueyrredón", 'api_districts_id' => '06357', 'api_states_id' => '06', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Mar Chiquita", 'api_districts_id' => '06518', 'api_states_id' => '06', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Villa Gesell", 'api_districts_id' => '06868', 'api_states_id' => '06', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Pinamar", 'api_districts_id' => '06644', 'api_states_id' => '06', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "General Lavalle", 'api_districts_id' => '06336', 'api_states_id' => '06', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "La Costa", 'api_districts_id' => '06420', 'api_states_id' => '06', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Magdalena", 'api_districts_id' => '06505', 'api_states_id' => '06', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Sauce", 'api_districts_id' => '18175', 'api_states_id' => '18', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Vicente López", 'api_districts_id' => '06861', 'api_states_id' => '06', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "La Viña", 'api_districts_id' => '66098', 'api_states_id' => '66', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Rauch", 'api_districts_id' => '06672', 'api_states_id' => '06', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Metán", 'api_districts_id' => '66112', 'api_states_id' => '66', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Molinos", 'api_districts_id' => '66119', 'api_states_id' => '66', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "O'Higgins", 'api_districts_id' => '22112', 'api_states_id' => '22', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Moreno", 'api_districts_id' => '06560', 'api_states_id' => '06', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "La Matanza", 'api_districts_id' => '06427', 'api_states_id' => '06', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Tandil", 'api_districts_id' => '06791', 'api_states_id' => '06', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Coronel Suárez", 'api_districts_id' => '06203', 'api_states_id' => '06', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Chamical", 'api_districts_id' => '46035', 'api_states_id' => '46', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Futaleufú", 'api_districts_id' => '26035', 'api_states_id' => '26', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Río Chico", 'api_districts_id' => '78049', 'api_states_id' => '78', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "San Antonio", 'api_districts_id' => '62077', 'api_states_id' => '62', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Alberdi", 'api_districts_id' => '86014', 'api_states_id' => '86', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Juan Felipe Ibarra", 'api_districts_id' => '86098', 'api_states_id' => '86', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "General Taboada", 'api_districts_id' => '86077', 'api_states_id' => '86', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Salliqueló", 'api_districts_id' => '06721', 'api_states_id' => '06', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Berazategui", 'api_districts_id' => '06091', 'api_states_id' => '06', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "General Güemes", 'api_districts_id' => '66049', 'api_states_id' => '66', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "San Carlos", 'api_districts_id' => '66154', 'api_states_id' => '66', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "General Paz", 'api_districts_id' => '06343', 'api_states_id' => '06', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "General Guido", 'api_districts_id' => '06308', 'api_states_id' => '06', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "General Juan Madariaga", 'api_districts_id' => '06315', 'api_states_id' => '06', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Lago Argentino", 'api_districts_id' => '78028', 'api_states_id' => '78', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Rivadavia", 'api_districts_id' => '86154', 'api_states_id' => '86', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Ojo de Agua", 'api_districts_id' => '86126', 'api_states_id' => '86', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Choya", 'api_districts_id' => '86063', 'api_states_id' => '86', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Gobernador Dupuy", 'api_districts_id' => '74042', 'api_states_id' => '74', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Cachi", 'api_districts_id' => '66014', 'api_states_id' => '66', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Chicoana", 'api_districts_id' => '66042', 'api_states_id' => '66', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Gaiman", 'api_districts_id' => '26042', 'api_states_id' => '26', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Rawson", 'api_districts_id' => '26077', 'api_states_id' => '26', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "General Lamadrid", 'api_districts_id' => '46077', 'api_states_id' => '46', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Ayacucho", 'api_districts_id' => '74007', 'api_states_id' => '74', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "12 de Octubre", 'api_districts_id' => '22036', 'api_states_id' => '22', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Tulumba", 'api_districts_id' => '14175', 'api_states_id' => '14', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Cruz del Eje", 'api_districts_id' => '14028', 'api_states_id' => '14', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Punilla", 'api_districts_id' => '14091', 'api_states_id' => '14', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Comuna 6", 'api_districts_id' => '02042', 'api_states_id' => '02', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Santa Rosa", 'api_districts_id' => '50112', 'api_states_id' => '50', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "General Güemes", 'api_districts_id' => '22063', 'api_states_id' => '22', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "General Ortiz de Ocampo", 'api_districts_id' => '46084', 'api_states_id' => '46', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "General Roca", 'api_districts_id' => '14035', 'api_states_id' => '14', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Pilagás", 'api_districts_id' => '34042', 'api_states_id' => '34', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Laishi", 'api_districts_id' => '34021', 'api_states_id' => '34', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Rivadavia", 'api_districts_id' => '50084', 'api_states_id' => '50', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Tornquist", 'api_districts_id' => '06819', 'api_states_id' => '06', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "La Paz", 'api_districts_id' => '50042', 'api_states_id' => '50', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Coronel Pringles", 'api_districts_id' => '06196', 'api_states_id' => '06', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Conesa", 'api_districts_id' => '62028', 'api_states_id' => '62', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Villarino", 'api_districts_id' => '06875', 'api_states_id' => '06', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Pirané", 'api_districts_id' => '34056', 'api_states_id' => '34', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "General Pinto", 'api_districts_id' => '06351', 'api_states_id' => '06', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "San Cayetano", 'api_districts_id' => '06742', 'api_states_id' => '06', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Tres Arroyos", 'api_districts_id' => '06833', 'api_states_id' => '06', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Coronel Dorrego", 'api_districts_id' => '06189', 'api_states_id' => '06', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Necochea", 'api_districts_id' => '06581', 'api_states_id' => '06', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Independencia", 'api_districts_id' => '46105', 'api_states_id' => '46', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Chascomús", 'api_districts_id' => '06218', 'api_states_id' => '06', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Punta Indio", 'api_districts_id' => '06655', 'api_states_id' => '06', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "El Carmen", 'api_districts_id' => '38014', 'api_states_id' => '38', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Santa María", 'api_districts_id' => '14147', 'api_states_id' => '14', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Valcheta", 'api_districts_id' => '62084', 'api_states_id' => '62', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Arauco", 'api_districts_id' => '46007', 'api_states_id' => '46', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Lezama", 'api_districts_id' => '06466', 'api_states_id' => '06', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Campana", 'api_districts_id' => '06126', 'api_states_id' => '06', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Magallanes", 'api_districts_id' => '78042', 'api_states_id' => '78', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Corpen Aike", 'api_districts_id' => '78007', 'api_states_id' => '78', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Minas", 'api_districts_id' => '14070', 'api_states_id' => '14', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "San Alberto", 'api_districts_id' => '14126', 'api_states_id' => '14', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Río Segundo", 'api_districts_id' => '14119', 'api_states_id' => '14', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "San Justo", 'api_districts_id' => '14140', 'api_states_id' => '14', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Unión", 'api_districts_id' => '14182', 'api_states_id' => '14', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Tercero Arriba", 'api_districts_id' => '14161', 'api_states_id' => '14', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Cerrillos", 'api_districts_id' => '66035', 'api_states_id' => '66', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Río Cuarto", 'api_districts_id' => '14098', 'api_states_id' => '14', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Tupungato", 'api_districts_id' => '50126', 'api_states_id' => '50', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "9 de Julio", 'api_districts_id' => '62049', 'api_states_id' => '62', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Ñorquinco", 'api_districts_id' => '62056', 'api_states_id' => '62', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "San Rafael", 'api_districts_id' => '50105', 'api_states_id' => '50', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Anta", 'api_districts_id' => '66007', 'api_states_id' => '66', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Picún Leufú", 'api_districts_id' => '58098', 'api_states_id' => '58', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Zapala", 'api_districts_id' => '58112', 'api_states_id' => '58', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "25 de Mayo", 'api_districts_id' => '62091', 'api_states_id' => '62', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Telsen", 'api_districts_id' => '26105', 'api_states_id' => '26', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Pilcaniyeu", 'api_districts_id' => '62070', 'api_states_id' => '62', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Adolfo Alsina", 'api_districts_id' => '06007', 'api_states_id' => '06', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "General Alvear", 'api_districts_id' => '50014', 'api_states_id' => '50', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "La Caldera", 'api_districts_id' => '66077', 'api_states_id' => '66', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Sargento Cabral", 'api_districts_id' => '22154', 'api_states_id' => '22', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Pellegrini", 'api_districts_id' => '06616', 'api_states_id' => '06', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Aluminé", 'api_districts_id' => '58007', 'api_states_id' => '58', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Iruya", 'api_districts_id' => '66070', 'api_states_id' => '66', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Lácar", 'api_districts_id' => '58056', 'api_states_id' => '58', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Fray Mamerto Esquiú", 'api_districts_id' => '10063', 'api_states_id' => '10', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Valle Viejo", 'api_districts_id' => '10112', 'api_states_id' => '10', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "San Cosme", 'api_districts_id' => '18133', 'api_states_id' => '18', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Sarmiento", 'api_districts_id' => '26091', 'api_states_id' => '26', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Comuna 1", 'api_districts_id' => '02007', 'api_states_id' => '02', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Comuna 4", 'api_districts_id' => '02028', 'api_states_id' => '02', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "El Cuy", 'api_districts_id' => '62035', 'api_states_id' => '62', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Las Heras", 'api_districts_id' => '50049', 'api_states_id' => '50', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Tapenagá", 'api_districts_id' => '22161', 'api_states_id' => '22', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Lavalle", 'api_districts_id' => '50056', 'api_states_id' => '50', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Malargüe", 'api_districts_id' => '50077', 'api_states_id' => '50', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Presidente Roque Sáenz Peña", 'api_districts_id' => '14084', 'api_states_id' => '14', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Catán Lil", 'api_districts_id' => '58021', 'api_states_id' => '58', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Presidencia de la Plaza", 'api_districts_id' => '22119', 'api_states_id' => '22', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Comuna 5", 'api_districts_id' => '02035', 'api_states_id' => '02', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Esquina", 'api_districts_id' => '18049', 'api_states_id' => '18', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Ushuaia", 'api_districts_id' => '94015', 'api_states_id' => '94', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Antofagasta de la Sierra", 'api_districts_id' => '10028', 'api_states_id' => '10', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Ensenada", 'api_districts_id' => '06245', 'api_states_id' => '06', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Capital", 'api_districts_id' => '90084', 'api_states_id' => '90', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Belgrano", 'api_districts_id' => '82007', 'api_states_id' => '82', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Pergamino", 'api_districts_id' => '06623', 'api_states_id' => '06', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Puán", 'api_districts_id' => '06651', 'api_states_id' => '06', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "General Villegas", 'api_districts_id' => '06392', 'api_states_id' => '06', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Comuna 12", 'api_districts_id' => '02084', 'api_states_id' => '02', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "General Obligado", 'api_districts_id' => '82049', 'api_states_id' => '82', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Vera", 'api_districts_id' => '82133', 'api_states_id' => '82', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "9 de Julio", 'api_districts_id' => '82077', 'api_states_id' => '82', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Adolfo Alsina", 'api_districts_id' => '62007', 'api_states_id' => '62', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Quitilipi", 'api_districts_id' => '22133', 'api_states_id' => '22', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Güer Aike", 'api_districts_id' => '78021', 'api_states_id' => '78', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Capayán", 'api_districts_id' => '10042', 'api_states_id' => '10', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Burruyacú", 'api_districts_id' => '90007', 'api_states_id' => '90', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "San Jerónimo", 'api_districts_id' => '82105', 'api_states_id' => '82', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Independencia", 'api_districts_id' => '22070', 'api_states_id' => '22', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Curuzú Cuatiá", 'api_districts_id' => '18035', 'api_states_id' => '18', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Luján de Cuyo", 'api_districts_id' => '50063', 'api_states_id' => '50', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Tinogasta", 'api_districts_id' => '10105', 'api_states_id' => '10', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Comuna 7", 'api_districts_id' => '02049', 'api_states_id' => '02', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Hucal", 'api_districts_id' => '42077', 'api_states_id' => '42', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Itatí", 'api_districts_id' => '18077', 'api_states_id' => '18', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Comuna 10", 'api_districts_id' => '02070', 'api_states_id' => '02', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Caleu Caleu", 'api_districts_id' => '42014', 'api_states_id' => '42', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Lihuel Calel", 'api_districts_id' => '42084', 'api_states_id' => '42', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Curacó", 'api_districts_id' => '42042', 'api_states_id' => '42', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Confluencia", 'api_districts_id' => '58035', 'api_states_id' => '58', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Picunches", 'api_districts_id' => '58105', 'api_states_id' => '58', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Añelo", 'api_districts_id' => '58014', 'api_states_id' => '58', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Loncopué", 'api_districts_id' => '58063', 'api_states_id' => '58', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Ñorquín", 'api_districts_id' => '58084', 'api_states_id' => '58', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Pehuenches", 'api_districts_id' => '58091', 'api_states_id' => '58', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Comuna 11", 'api_districts_id' => '02077', 'api_states_id' => '02', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Montecarlo", 'api_districts_id' => '54084', 'api_states_id' => '54', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Eldorado", 'api_districts_id' => '54042', 'api_states_id' => '54', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "San Pedro", 'api_districts_id' => '54112', 'api_states_id' => '54', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Antártida Argentina", 'api_districts_id' => '94028', 'api_states_id' => '94', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Minas", 'api_districts_id' => '58077', 'api_states_id' => '58', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Chos Malal", 'api_districts_id' => '58042', 'api_states_id' => '58', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Cushamen", 'api_districts_id' => '26014', 'api_states_id' => '26', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Lago Buenos Aires", 'api_districts_id' => '78035', 'api_states_id' => '78', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Pichi Mahuida", 'api_districts_id' => '62063', 'api_states_id' => '62', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "San Martín", 'api_districts_id' => '86175', 'api_states_id' => '86', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Yavi", 'api_districts_id' => '38112', 'api_states_id' => '38', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Santa Catalina", 'api_districts_id' => '38077', 'api_states_id' => '38', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "San Pedro", 'api_districts_id' => '38063', 'api_states_id' => '38', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Valle Grande", 'api_districts_id' => '38105', 'api_states_id' => '38', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Patiño", 'api_districts_id' => '34035', 'api_states_id' => '34', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Bermejo", 'api_districts_id' => '34007', 'api_states_id' => '34', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Susques", 'api_districts_id' => '38084', 'api_states_id' => '38', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Matacos", 'api_districts_id' => '34028', 'api_states_id' => '34', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Los Andes", 'api_districts_id' => '66105', 'api_states_id' => '66', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Orán", 'api_districts_id' => '66126', 'api_states_id' => '66', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Tilcara", 'api_districts_id' => '38094', 'api_states_id' => '38', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Palpalá", 'api_districts_id' => '38042', 'api_states_id' => '38', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Loventué", 'api_districts_id' => '42098', 'api_states_id' => '42', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Río Senguer", 'api_districts_id' => '26084', 'api_states_id' => '26', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Bariloche", 'api_districts_id' => '62021', 'api_states_id' => '62', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Huiliches", 'api_districts_id' => '58049', 'api_states_id' => '58', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Limay Mahuida", 'api_districts_id' => '42091', 'api_states_id' => '42', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Puelén", 'api_districts_id' => '42112', 'api_states_id' => '42', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Chalileo", 'api_districts_id' => '42049', 'api_states_id' => '42', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Chical Co", 'api_districts_id' => '42063', 'api_states_id' => '42', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Quebrachos", 'api_districts_id' => '86140', 'api_states_id' => '86', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Monte Caseros", 'api_districts_id' => '18112', 'api_states_id' => '18', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Mayor Luis J. Fontana", 'api_districts_id' => '22098', 'api_states_id' => '22', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Fray Justo Santa María de Oro", 'api_districts_id' => '22043', 'api_states_id' => '22', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "General Belgrano", 'api_districts_id' => '46063', 'api_states_id' => '46', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Las Colonias", 'api_districts_id' => '82070', 'api_states_id' => '82', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "San Justo", 'api_districts_id' => '82112', 'api_states_id' => '82', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "San Cristóbal", 'api_districts_id' => '82091', 'api_states_id' => '82', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "San Javier", 'api_districts_id' => '82098', 'api_states_id' => '82', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Chapaleufú", 'api_districts_id' => '42056', 'api_states_id' => '42', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Realicó", 'api_districts_id' => '42133', 'api_states_id' => '42', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Maracó", 'api_districts_id' => '42105', 'api_states_id' => '42', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Trenel", 'api_districts_id' => '42147', 'api_states_id' => '42', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Copo", 'api_districts_id' => '86056', 'api_states_id' => '86', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Capital", 'api_districts_id' => '42021', 'api_states_id' => '42', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Santa Bárbara", 'api_districts_id' => '38070', 'api_states_id' => '38', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Almirante Brown", 'api_districts_id' => '22007', 'api_states_id' => '22', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Rosario de la Frontera", 'api_districts_id' => '66140', 'api_states_id' => '66', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Collón Curá", 'api_districts_id' => '58028', 'api_states_id' => '58', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Comuna 3", 'api_districts_id' => '02021', 'api_states_id' => '02', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "San Fernando", 'api_districts_id' => '06749', 'api_states_id' => '06', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Tigre", 'api_districts_id' => '06805', 'api_states_id' => '06', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Santa María", 'api_districts_id' => '10091', 'api_states_id' => '10', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Santa Rosa", 'api_districts_id' => '10098', 'api_states_id' => '10', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "La Paz", 'api_districts_id' => '10070', 'api_states_id' => '10', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Río Hondo", 'api_districts_id' => '86147', 'api_states_id' => '86', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Vinchina", 'api_districts_id' => '46098', 'api_states_id' => '46', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Capital", 'api_districts_id' => '46014', 'api_states_id' => '46', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Río Seco", 'api_districts_id' => '14112', 'api_states_id' => '14', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Avellaneda", 'api_districts_id' => '62014', 'api_states_id' => '62', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "General Roca", 'api_districts_id' => '62042', 'api_states_id' => '62', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Belgrano", 'api_districts_id' => '74014', 'api_states_id' => '74', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Los Lagos", 'api_districts_id' => '58070', 'api_states_id' => '58', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Capital", 'api_districts_id' => '10049', 'api_states_id' => '10', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Ancasti", 'api_districts_id' => '10014', 'api_states_id' => '10', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Pomán", 'api_districts_id' => '10084', 'api_states_id' => '10', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Comuna 2", 'api_districts_id' => '02014', 'api_states_id' => '02', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "9 de Julio", 'api_districts_id' => '22105', 'api_states_id' => '22', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Pocho", 'api_districts_id' => '14077', 'api_states_id' => '14', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Ezeiza", 'api_districts_id' => '06270', 'api_states_id' => '06', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Andalgalá", 'api_districts_id' => '10021', 'api_states_id' => '10', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Ambato", 'api_districts_id' => '10007', 'api_states_id' => '10', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Comuna 8", 'api_districts_id' => '02056', 'api_states_id' => '02', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Guasayán", 'api_districts_id' => '86084', 'api_states_id' => '86', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Paclín", 'api_districts_id' => '10077', 'api_states_id' => '10', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "El Alto", 'api_districts_id' => '10056', 'api_states_id' => '10', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Sobremonte", 'api_districts_id' => '14154', 'api_states_id' => '14', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Río Grande", 'api_districts_id' => '94008', 'api_states_id' => '94', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Comuna 13", 'api_districts_id' => '02091', 'api_states_id' => '02', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Banda", 'api_districts_id' => '86035', 'api_states_id' => '86', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Paso de Indios", 'api_districts_id' => '26070', 'api_states_id' => '26', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Capital", 'api_districts_id' => '14014', 'api_states_id' => '14', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Mártires", 'api_districts_id' => '26063', 'api_states_id' => '26', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Sarmiento", 'api_districts_id' => '86182', 'api_states_id' => '86', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Deseado", 'api_districts_id' => '78014', 'api_states_id' => '78', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Languiñeo", 'api_districts_id' => '26056', 'api_states_id' => '26', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Belgrano", 'api_districts_id' => '86042', 'api_states_id' => '86', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Aguirre", 'api_districts_id' => '86007', 'api_states_id' => '86', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Maipú", 'api_districts_id' => '22091', 'api_states_id' => '22', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "San Carlos", 'api_districts_id' => '50091', 'api_states_id' => '50', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Tunuyán", 'api_districts_id' => '50119', 'api_states_id' => '50', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Robles", 'api_districts_id' => '86161', 'api_states_id' => '86', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Loreto", 'api_districts_id' => '86105', 'api_states_id' => '86', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Catriló", 'api_districts_id' => '42028', 'api_states_id' => '42', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Capital", 'api_districts_id' => '86049', 'api_states_id' => '86', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Comuna 14", 'api_districts_id' => '02098', 'api_states_id' => '02', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Colón", 'api_districts_id' => '30008', 'api_states_id' => '30', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Villaguay", 'api_districts_id' => '30113', 'api_states_id' => '30', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Castelli", 'api_districts_id' => '06168', 'api_states_id' => '06', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "San Salvador", 'api_districts_id' => '30088', 'api_states_id' => '30', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Belén", 'api_districts_id' => '10035', 'api_states_id' => '10', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Almirante Brown", 'api_districts_id' => '06028', 'api_states_id' => '06', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Nogoyá", 'api_districts_id' => '30077', 'api_states_id' => '30', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Tala", 'api_districts_id' => '30091', 'api_states_id' => '30', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Gualeguay", 'api_districts_id' => '30049', 'api_states_id' => '30', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Federación", 'api_districts_id' => '30028', 'api_states_id' => '30', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "La Paz", 'api_districts_id' => '30070', 'api_states_id' => '30', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Feliciano", 'api_districts_id' => '30042', 'api_states_id' => '30', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Presidente Perón", 'api_districts_id' => '06648', 'api_states_id' => '06', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Junín", 'api_districts_id' => '06413', 'api_states_id' => '06', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Brandsen", 'api_districts_id' => '06119', 'api_states_id' => '06', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Chivilcoy", 'api_districts_id' => '06224', 'api_states_id' => '06', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Alberti", 'api_districts_id' => '06021', 'api_states_id' => '06', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Bragado", 'api_districts_id' => '06112', 'api_states_id' => '06', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "General Las Heras", 'api_districts_id' => '06329', 'api_states_id' => '06', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Carlos Casares", 'api_districts_id' => '06147', 'api_states_id' => '06', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Marcos Paz", 'api_districts_id' => '06525', 'api_states_id' => '06', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "General Viamonte", 'api_districts_id' => '06385', 'api_states_id' => '06', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Carlos Tejedor", 'api_districts_id' => '06154', 'api_states_id' => '06', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "25 de Mayo", 'api_districts_id' => '06854', 'api_states_id' => '06', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "9 de Julio", 'api_districts_id' => '06588', 'api_states_id' => '06', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Pehuajó", 'api_districts_id' => '06609', 'api_states_id' => '06', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Tapalqué", 'api_districts_id' => '06798', 'api_states_id' => '06', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Trenque Lauquen", 'api_districts_id' => '06826', 'api_states_id' => '06', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "General Belgrano", 'api_districts_id' => '06301', 'api_states_id' => '06', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Monte", 'api_districts_id' => '06547', 'api_states_id' => '06', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Roque Pérez", 'api_districts_id' => '06693', 'api_states_id' => '06', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Olavarría", 'api_districts_id' => '06595', 'api_states_id' => '06', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Merlo", 'api_districts_id' => '06539', 'api_states_id' => '06', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Cainguás", 'api_districts_id' => '54014', 'api_states_id' => '54', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Islas del Atlántico Sur", 'api_districts_id' => '94021', 'api_states_id' => '94', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Esteban Echeverría", 'api_districts_id' => '06260', 'api_states_id' => '06', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Arrecifes", 'api_districts_id' => '06077', 'api_states_id' => '06', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Capitán Sarmiento", 'api_districts_id' => '06140', 'api_states_id' => '06', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Dr. Manuel Belgrano", 'api_districts_id' => '38021', 'api_states_id' => '38', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Carmen de Areco", 'api_districts_id' => '06161', 'api_states_id' => '06', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Salto", 'api_districts_id' => '06714', 'api_states_id' => '06', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Exaltación de la Cruz", 'api_districts_id' => '06266', 'api_states_id' => '06', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "San Miguel", 'api_districts_id' => '06760', 'api_states_id' => '06', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "San Andrés de Giles", 'api_districts_id' => '06728', 'api_states_id' => '06', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Mercedes", 'api_districts_id' => '06532', 'api_states_id' => '06', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Pilar", 'api_districts_id' => '06638', 'api_states_id' => '06', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Luján", 'api_districts_id' => '06497', 'api_states_id' => '06', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Famaillá", 'api_districts_id' => '90028', 'api_states_id' => '90', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Hurlingham", 'api_districts_id' => '06408', 'api_states_id' => '06', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Morón", 'api_districts_id' => '06568', 'api_states_id' => '06', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Chacabuco", 'api_districts_id' => '06210', 'api_states_id' => '06', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Junín", 'api_districts_id' => '50035', 'api_states_id' => '50', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Malvinas Argentinas", 'api_districts_id' => '06515', 'api_states_id' => '06', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Tres Lomas", 'api_districts_id' => '06847', 'api_states_id' => '06', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Ayacucho", 'api_districts_id' => '06042', 'api_states_id' => '06', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Guaminí", 'api_districts_id' => '06399', 'api_states_id' => '06', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "General San Martín", 'api_districts_id' => '06371', 'api_states_id' => '06', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Lincoln", 'api_districts_id' => '06469', 'api_states_id' => '06', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Laprida", 'api_districts_id' => '06448', 'api_states_id' => '06', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "San Isidro", 'api_districts_id' => '06756', 'api_states_id' => '06', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Benito Juárez", 'api_districts_id' => '06084', 'api_states_id' => '06', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Colón", 'api_districts_id' => '06175', 'api_states_id' => '06', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Ituzaingó", 'api_districts_id' => '06410', 'api_states_id' => '06', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "General Rodríguez", 'api_districts_id' => '06364', 'api_states_id' => '06', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Suipacha", 'api_districts_id' => '06784', 'api_states_id' => '06', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Tres de Febrero", 'api_districts_id' => '06840', 'api_states_id' => '06', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "General Felipe Varela", 'api_districts_id' => '46028', 'api_states_id' => '46', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Florencio Varela", 'api_districts_id' => '06274', 'api_states_id' => '06', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Navarro", 'api_districts_id' => '06574', 'api_states_id' => '06', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Cañuelas", 'api_districts_id' => '06134', 'api_states_id' => '06', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Moreno", 'api_districts_id' => '86119', 'api_states_id' => '86', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Chacabuco", 'api_districts_id' => '22028', 'api_states_id' => '22', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "San Vicente", 'api_districts_id' => '06778', 'api_states_id' => '06', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Lobos", 'api_districts_id' => '06483', 'api_states_id' => '06', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "General Alvear", 'api_districts_id' => '06287', 'api_states_id' => '06', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Quilmes", 'api_districts_id' => '06658', 'api_states_id' => '06', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Pila", 'api_districts_id' => '06630', 'api_states_id' => '06', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "General La Madrid", 'api_districts_id' => '06322', 'api_states_id' => '06', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Bolívar", 'api_districts_id' => '06105', 'api_states_id' => '06', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Castro Barros", 'api_districts_id' => '46021', 'api_states_id' => '46', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Balcarce", 'api_districts_id' => '06063', 'api_states_id' => '06', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Hipólito Yrigoyen", 'api_districts_id' => '06406', 'api_states_id' => '06', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Capital", 'api_districts_id' => '50007', 'api_states_id' => '50', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Dolores", 'api_districts_id' => '06238', 'api_states_id' => '06', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Azul", 'api_districts_id' => '06049', 'api_states_id' => '06', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Daireaux", 'api_districts_id' => '06231', 'api_states_id' => '06', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Godoy Cruz", 'api_districts_id' => '50021', 'api_states_id' => '50', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Cafayate", 'api_districts_id' => '66021', 'api_states_id' => '66', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Figueroa", 'api_districts_id' => '86070', 'api_states_id' => '86', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Saavedra", 'api_districts_id' => '06700', 'api_states_id' => '06', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Monte Hermoso", 'api_districts_id' => '06553', 'api_states_id' => '06', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Lobería", 'api_districts_id' => '06476', 'api_states_id' => '06', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Berisso", 'api_districts_id' => '06098', 'api_states_id' => '06', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Tordillo", 'api_districts_id' => '06812', 'api_states_id' => '06', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Zárate", 'api_districts_id' => '06882', 'api_states_id' => '06', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Ramallo", 'api_districts_id' => '06665', 'api_states_id' => '06', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "San Nicolás", 'api_districts_id' => '06763', 'api_states_id' => '06', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Salavina", 'api_districts_id' => '86168', 'api_states_id' => '86', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Pellegrini", 'api_districts_id' => '86133', 'api_states_id' => '86', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Avellaneda", 'api_districts_id' => '86028', 'api_states_id' => '86', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "2 de Abril", 'api_districts_id' => '22039', 'api_states_id' => '22', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Guaymallén", 'api_districts_id' => '50028', 'api_states_id' => '50', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Juárez Celman", 'api_districts_id' => '14056', 'api_states_id' => '14', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Capital", 'api_districts_id' => '66028', 'api_states_id' => '66', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Silípica", 'api_districts_id' => '86189', 'api_states_id' => '86', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "La Candelaria", 'api_districts_id' => '66084', 'api_states_id' => '66', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Rancul", 'api_districts_id' => '42126', 'api_states_id' => '42', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Maipú", 'api_districts_id' => '50070', 'api_states_id' => '50', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Guachipas", 'api_districts_id' => '66063', 'api_states_id' => '66', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Atreucó", 'api_districts_id' => '42007', 'api_states_id' => '42', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "San Martín", 'api_districts_id' => '50098', 'api_states_id' => '50', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Guatraché", 'api_districts_id' => '42070', 'api_states_id' => '42', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Sanagasta", 'api_districts_id' => '46126', 'api_states_id' => '46', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Conhelo", 'api_districts_id' => '42035', 'api_states_id' => '42', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Libertador General San Martín", 'api_districts_id' => '54077', 'api_states_id' => '54', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Rosario Vera Peñaloza", 'api_districts_id' => '46112', 'api_states_id' => '46', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "San Miguel", 'api_districts_id' => '18154', 'api_states_id' => '18', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "General Juan Facundo Quiroga", 'api_districts_id' => '46070', 'api_states_id' => '46', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Ángel Vicente Peñaloza", 'api_districts_id' => '46056', 'api_states_id' => '46', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Empedrado", 'api_districts_id' => '18042', 'api_states_id' => '18', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Chilecito", 'api_districts_id' => '46042', 'api_states_id' => '46', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Toay", 'api_districts_id' => '42140', 'api_states_id' => '42', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Colón", 'api_districts_id' => '14021', 'api_states_id' => '14', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Ituzaingó", 'api_districts_id' => '18084', 'api_states_id' => '18', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Famatina", 'api_districts_id' => '46049', 'api_states_id' => '46', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "General López", 'api_districts_id' => '82042', 'api_states_id' => '82', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Constitución", 'api_districts_id' => '82028', 'api_states_id' => '82', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Caseros", 'api_districts_id' => '82014', 'api_states_id' => '82', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Rosario", 'api_districts_id' => '82084', 'api_states_id' => '82', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "San Lorenzo", 'api_districts_id' => '82119', 'api_states_id' => '82', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Iriondo", 'api_districts_id' => '82056', 'api_states_id' => '82', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Lanús", 'api_districts_id' => '06434', 'api_states_id' => '06', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "General San Martín", 'api_districts_id' => '46091', 'api_states_id' => '46', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "San Blas de Los Sauces", 'api_districts_id' => '46119', 'api_states_id' => '46', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "San Antonio", 'api_districts_id' => '38056', 'api_states_id' => '38', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Rinconada", 'api_districts_id' => '38049', 'api_states_id' => '38', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Ramón Lista", 'api_districts_id' => '34063', 'api_states_id' => '34', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "La Poma", 'api_districts_id' => '66091', 'api_states_id' => '66', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Biedma", 'api_districts_id' => '26007', 'api_states_id' => '26', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Capital", 'api_districts_id' => '18021', 'api_states_id' => '18', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "San Luis del Palmar", 'api_districts_id' => '18140', 'api_states_id' => '18', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Formosa", 'api_districts_id' => '34014', 'api_states_id' => '34', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Pilcomayo", 'api_districts_id' => '34049', 'api_states_id' => '34', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Tehuelches", 'api_districts_id' => '26098', 'api_states_id' => '26', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Escalante", 'api_districts_id' => '26021', 'api_states_id' => '26', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Ischilín", 'api_districts_id' => '14049', 'api_states_id' => '14', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Totoral", 'api_districts_id' => '14168', 'api_states_id' => '14', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "General San Martín", 'api_districts_id' => '14042', 'api_states_id' => '14', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "San Javier", 'api_districts_id' => '14133', 'api_states_id' => '14', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Río Primero", 'api_districts_id' => '14105', 'api_states_id' => '14', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Marcos Juárez", 'api_districts_id' => '14063', 'api_states_id' => '14', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "General Donovan", 'api_districts_id' => '22056', 'api_states_id' => '22', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Leandro N. Alem", 'api_districts_id' => '06462', 'api_states_id' => '06', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Libertador General San Martín", 'api_districts_id' => '22084', 'api_states_id' => '22', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Gastre", 'api_districts_id' => '26049', 'api_states_id' => '26', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "General Arenales", 'api_districts_id' => '06294', 'api_states_id' => '06', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Bermejo", 'api_districts_id' => '22014', 'api_states_id' => '22', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Calamuchita", 'api_districts_id' => '14007', 'api_states_id' => '14', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Cruz Alta", 'api_districts_id' => '90014', 'api_states_id' => '90', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Lules", 'api_districts_id' => '90063', 'api_states_id' => '90', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Yerba Buena", 'api_districts_id' => '90119', 'api_states_id' => '90', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Tafí Viejo", 'api_districts_id' => '90105', 'api_states_id' => '90', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Libertador General San Martín", 'api_districts_id' => '74063', 'api_states_id' => '74', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Coronel Pringles", 'api_districts_id' => '74021', 'api_states_id' => '74', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Chacabuco", 'api_districts_id' => '74028', 'api_states_id' => '74', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Rivadavia", 'api_districts_id' => '06679', 'api_states_id' => '06', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Patagones", 'api_districts_id' => '06602', 'api_states_id' => '06', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Juan Martín de Pueyrredón", 'api_districts_id' => '74056', 'api_states_id' => '74', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "General Pedernera", 'api_districts_id' => '74035', 'api_states_id' => '74', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Trancas", 'api_districts_id' => '90112', 'api_states_id' => '90', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Tafí del Valle", 'api_districts_id' => '90098', 'api_states_id' => '90', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Comuna 9", 'api_districts_id' => '02063', 'api_states_id' => '02', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Junín", 'api_districts_id' => '74049', 'api_states_id' => '74', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Mitre", 'api_districts_id' => '86112', 'api_states_id' => '86', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Atamisqui", 'api_districts_id' => '86021', 'api_states_id' => '86', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Berón de Astrada", 'api_districts_id' => '18014', 'api_states_id' => '18', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Tolhuin", 'api_districts_id' => '94011', 'api_states_id' => '94', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Capital", 'api_districts_id' => '54028', 'api_states_id' => '54', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Candelaria", 'api_districts_id' => '54021', 'api_states_id' => '54', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Jiménez", 'api_districts_id' => '86091', 'api_states_id' => '86', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Coronel de Marina Leonardo Rosales", 'api_districts_id' => '06182', 'api_states_id' => '06', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Baradero", 'api_districts_id' => '06070', 'api_states_id' => '06', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "San Pedro", 'api_districts_id' => '06770', 'api_states_id' => '06', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Santa Victoria", 'api_districts_id' => '66161', 'api_states_id' => '66', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "General José de San Martín", 'api_districts_id' => '66056', 'api_states_id' => '66', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Rivadavia", 'api_districts_id' => '66133', 'api_states_id' => '66', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Rosario de Lerma", 'api_districts_id' => '66147', 'api_states_id' => '66', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Ledesma", 'api_districts_id' => '38035', 'api_states_id' => '38', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Humahuaca", 'api_districts_id' => '38028', 'api_states_id' => '38', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Cochinoca", 'api_districts_id' => '38007', 'api_states_id' => '38', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Tumbaya", 'api_districts_id' => '38098', 'api_states_id' => '38', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Florentino Ameghino", 'api_districts_id' => '06277', 'api_states_id' => '06', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Florentino Ameghino", 'api_districts_id' => '26028', 'api_states_id' => '26', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "La Cocha", 'api_districts_id' => '90049', 'api_states_id' => '90', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Graneros", 'api_districts_id' => '90035', 'api_states_id' => '90', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Juan Bautista Alberdi", 'api_districts_id' => '90042', 'api_states_id' => '90', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Río Chico", 'api_districts_id' => '90077', 'api_states_id' => '90', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Simoca", 'api_districts_id' => '90091', 'api_states_id' => '90', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Chicligasta", 'api_districts_id' => '90021', 'api_states_id' => '90', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Monteros", 'api_districts_id' => '90070', 'api_states_id' => '90', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Leales", 'api_districts_id' => '90056', 'api_states_id' => '90', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "San Martín", 'api_districts_id' => '82126', 'api_states_id' => '82', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "La Capital", 'api_districts_id' => '82063', 'api_states_id' => '82', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "General Manuel Belgrano", 'api_districts_id' => '54049', 'api_states_id' => '54', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Guaraní", 'api_districts_id' => '54056', 'api_states_id' => '54', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Iguazú", 'api_districts_id' => '54063', 'api_states_id' => '54', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "25 de Mayo", 'api_districts_id' => '54119', 'api_states_id' => '54', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Oberá", 'api_districts_id' => '54091', 'api_states_id' => '54', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Castellanos", 'api_districts_id' => '82021', 'api_states_id' => '82', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Garay", 'api_districts_id' => '82035', 'api_states_id' => '82', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Quemú Quemú", 'api_districts_id' => '42119', 'api_states_id' => '42', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "San Ignacio", 'api_districts_id' => '54098', 'api_states_id' => '54', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Utracán", 'api_districts_id' => '42154', 'api_states_id' => '42', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "San Martín", 'api_districts_id' => '18147', 'api_states_id' => '18', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Paso de los Libres", 'api_districts_id' => '18119', 'api_states_id' => '18', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Goya", 'api_districts_id' => '18070', 'api_states_id' => '18', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Lavalle", 'api_districts_id' => '18091', 'api_states_id' => '18', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "San Roque", 'api_districts_id' => '18161', 'api_states_id' => '18', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "General Alvear", 'api_districts_id' => '18056', 'api_states_id' => '18', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Concepción", 'api_districts_id' => '18028', 'api_states_id' => '18', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Bella Vista", 'api_districts_id' => '18007', 'api_states_id' => '18', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Santo Tomé", 'api_districts_id' => '18168', 'api_states_id' => '18', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Saladas", 'api_districts_id' => '18126', 'api_states_id' => '18', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "General Paz", 'api_districts_id' => '18063', 'api_states_id' => '18', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Leandro N. Alem", 'api_districts_id' => '54070', 'api_states_id' => '54', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "San Javier", 'api_districts_id' => '54105', 'api_states_id' => '54', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Mburucuyá", 'api_districts_id' => '18098', 'api_states_id' => '18', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Concepción", 'api_districts_id' => '54035', 'api_states_id' => '54', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Apóstoles", 'api_districts_id' => '54007', 'api_states_id' => '54', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "1° de Mayo", 'api_districts_id' => '22126', 'api_states_id' => '22', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "San Fernando", 'api_districts_id' => '22140', 'api_states_id' => '22', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "San Lorenzo", 'api_districts_id' => '22147', 'api_states_id' => '22', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Lomas de Zamora", 'api_districts_id' => '06490', 'api_states_id' => '06', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Avellaneda", 'api_districts_id' => '06035', 'api_states_id' => '06', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "25 de Mayo", 'api_districts_id' => '22168', 'api_states_id' => '22', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "General Belgrano", 'api_districts_id' => '22049', 'api_states_id' => '22', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Libertad", 'api_districts_id' => '22077', 'api_states_id' => '22', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Comandante Fernández", 'api_districts_id' => '22021', 'api_states_id' => '22', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Comuna 15", 'api_districts_id' => '02105', 'api_states_id' => '02', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Chimbas", 'api_districts_id' => '70042', 'api_states_id' => '70', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Capital", 'api_districts_id' => '70028', 'api_states_id' => '70', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Rivadavia", 'api_districts_id' => '70084', 'api_states_id' => '70', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "9 de Julio", 'api_districts_id' => '70063', 'api_states_id' => '70', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Albardón", 'api_districts_id' => '70007', 'api_states_id' => '70', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Angaco", 'api_districts_id' => '70014', 'api_states_id' => '70', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Santa Lucía", 'api_districts_id' => '70098', 'api_states_id' => '70', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Rawson", 'api_districts_id' => '70077', 'api_states_id' => '70', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "25 de Mayo", 'api_districts_id' => '70126', 'api_states_id' => '70', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "San Martín", 'api_districts_id' => '70091', 'api_states_id' => '70', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Pocito", 'api_districts_id' => '70070', 'api_states_id' => '70', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Zonda", 'api_districts_id' => '70133', 'api_states_id' => '70', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Ullum", 'api_districts_id' => '70112', 'api_states_id' => '70', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Sarmiento", 'api_districts_id' => '70105', 'api_states_id' => '70', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Calingasta", 'api_districts_id' => '70021', 'api_states_id' => '70', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Iglesia", 'api_districts_id' => '70049', 'api_states_id' => '70', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Jáchal", 'api_districts_id' => '70056', 'api_states_id' => '70', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Valle Fértil", 'api_districts_id' => '70119', 'api_states_id' => '70', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Caucete", 'api_districts_id' => '70035', 'api_states_id' => '70', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "La Plata", 'api_districts_id' => '06441', 'api_states_id' => '06', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],
            ['name' => "Mercedes", 'api_districts_id' => '18105', 'api_states_id' => '18', 'audi_user' => 1, 'audi_date' => date('Y-m-d H:i:s'), 'audi_action' => 'I'],

        ];

        $this->db->table('districts')->insertBatch($data);
    }
}
